version: "3.8"
services:
  backend:
    build: .
    container_name: backend-chat
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file: .env
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo-chat
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
